@echo off
color 0a
title Anonymous CMD

echo MMMMMMMMMMMNmMNNNNNMMMMMNNNmNNmNdNNNdmNmmhhmNmmmmdNmNddNNmmNdNNNdmNmNmNmNNmNNmNNmMMmmMNNMMMNMMMMMMMM
echo MMMMMMMMNMMmNNNmmNNNNNNNmNNhNNmNhmNNhmNdmhhmmhhmddNdmhdNNmmNhNNNhmNmhNNmNmmNNNNmmNMmmMNNMMMNMMMMMMMM
echo MMNNMMMNNMMmmNNmNmNNdNNNmmNdNmmmhmNNhdNddyhdmhhddhmdmdhNNmdNymNNhmNmhdNmNmdNmmNmdNNNNNNNMMMNNMMMMMMM
echo MMMNMMMNNNMmmmNmNmNNdNNNmmmhNmdmhmNNyyNddddmmhdmhdmdmhhmmddmhmNNhmNhdhNmNmdNNmNNdNNddNNmMMMmNMMMMMMM
echo MMNNMMMNNMMmmmNmmNNNdNNNmmNhNmdmhmmmhdmhddymmhdmdmmmdhhNmmdmymmmhdmmymmdmddNddmNdNNdmNmmNNMmNMMMMMMM
echo MMmmMMMNmNNNmmNdmNNNhNNNdmmymmdmymmmhhmddddmmddmdmmmmdhNNmdmdmmmydmdydmdmmdNdmmmdNNmdNmmNNNmNMMMMMMM
echo MMNmNMMNNNNNNdNNNNNNymNmdmmymmmmydmmhhmmmddmNdmNmmNmNmmNNmmmhmmmhdmmydmdmdhmddmdhNNdhNmmNNNmmMMmNMMM
echo MMmmNNNmmmNNmmmmNNNmhmmdddmymmmmhmmmhdNmmmmNNmmNNNNNNmmNNNmNdmNNhmmmydmdmdhmddmmdmNhhNmdNNNmmNNmmMMM
echo MMNNNNNmmNNNdmddmNNmymmhhmmymmmmhmmNdmNmmmNNNNNNNNNNNNNNNNNNmNNNdmmmydmhmdhmddmmhmmdhNddNNNmmNNmNMMM
echo MMMNmNNdmmNNddmdmmmmhmddhmdymmmmdmNNmmNNNNNNNNNmmmmmmmNNNNNNmNNNmmmddhmdddhmdhdhhmmhhNmdNNNmmNNmmNMN
echo MMMmdNNmmmNNdmddmmmmymdhhmdhmmmmdmNNmNNNNNmmmmmmmmmmmmmmmmNNNNNNmmNmdmmddhymhhdhhmmdyNddNNNdmNNmmNNN
echo MNNNdNNNdNNNmmmdmmmmymmhdmmmmmmmmmNNNNNNmmmmmmmmmmmmmmmmmmmmmNNNmNNmdmmdmdhmhdddymmhhmdhNNNddNNmmNNN
echo NNNNdNNmdmNNmhmhmmmmyddhhmmmmmmmmNNNNNNmmmmmmmmmmmmmmmmmmmmmmmNNNNNNmmmdmdhdhhddymmhymddNNNdmmNddNNN
echo NNNNdNNmdNNmmddhmmmmyddhdmmmmmmmmNNNNNmmmmmNmNmmmmmmmNmmmmmmmmNNNNNNNmmdmdhdhhdhhmmyymmhNNNdmdddmNNN
echo NNNmdNNmdmNNhddhmmmdyddhdmmmmmmmmNNNNmmmmmmmmmmmmmmmmmmmmmmmmmmNNNNNNNmdmdhmhhddymmhhmdhNmddmdmmmNNN
echo NNNNdNNddmNmddddmmmdsddhdmmmmmmNmNNNNmmmmmmmmmmmmmmmmmmmmmmmmmmNNNNNNNmmmdhmdydhymmhymddmmhhdmmdmNNN
echo NNNmdNNmmmNmhddhmmmmyddhhmmmmmmmmNNMMNmmmmmmmmmmmmmmmmmmmmmmmmNNMNNNNNNmmdhdhhddymmmmmdhmdhhmmmddNNN
echo NNNNdNNdddNmdddhmmmdyddhhmmmmmmmNNNMMNNmmmNNNMNNmmmmNNMNNNmmmmNNMNNNNNmmmdhmdyddymddmmdhmdhmNddddNNN
echo NNNmdNNmmmNmmhmhmmmdsddhdmmmmmmmmNNNMMmmNMMMMMMMNmmmMMMMMMNmmmNMNNNNmNmmmdhmddddymdhmmdhmddmNmmmmNNN
echo NNNmdNNmdNNmdhmhmmmmyddhhmmmmmmmmNNNNMNmmNMMMMMNNmmmNMMMMMNmmNNNNNNNmNmmmdhdddhsymdhmmdhNmymNddddNNN
echo NNNNdNNmdmNNmhmhmmmmyddhhmmmdmmmmNNNNNmmmmmNNNmmmMNmmmNNmmmmmmmNNNNmNmmdmdhdhdysymdhmmdhNmhmNmmddNNN
echo NNNmdNNddmmmmmmhmmmmyddhhmmdddmmmNNNNNNmmmmmmmmmNMMNmmmmmmmmmNNNNNNmmmmdmdhmhdyyhmddmmmdNmhmNdmdmNNN
echo MNNmdNNmmmmhmNmdmmmmymdhdmmmdmmmNNNNNNNNNNNNmmmmNNNNmmmNNNNNNNNNNmmmmmmdmhymhdyymmmhmmmNNdddNdmmmNNN
echo MMNNmNNdmmdddNmdmdmmymmhhmmddmdmNNNNmNNNNNNNNmmmmmmmmmmNNMNMNNmNNmmmmmmdddhmhmyymmddmmmNNdhmNmmmmNNN
echo MMNNmNNmmmdmdNNdmhdmymmhhmmdddddmmNmmNNmNNNNNNmmmmmmmmmNNNNNNNmmNdmdmmmdmmdmhmdymmmmNdmNNmdNNmmmmNMN
echo MMMmmNNNmNddhNNdNhmmymdhymmdhhdhmmNmmmNmmNNmNNNNNNNNNNmNNNNNNNddmdmddmmhmdmmdmhymmmdNmmNNNdNNmmmNMMM
echo MMMNmNNNmNmmmNNmNhmmymmyymmdddhhmmmmmmmmmNmmNmNNmNNNNmmmmNNNNmddmhdddmmhmddmhmdymNmdNmmNNmdmNmmmmMMM
echo MMMNmNNNmNNdNNNdNdmNhmmhymmddhdhmmmmdmmddNddNmmNmNNmNmdmmNNNNmdmmhddhmmhmddmdmhhmNmmNmNNNmdNNNNmNMMM
echo MMMNmMMNNNNdNNNmNdmNmNmhhNmmddhdmmmdddmhdmhhNdmNdNNmmNNmmmNNmmhdmydddmmmmdmNdmhhNNmmNmNNNmmNNmmmNMMM
echo MMMNNMMMMNNmNNNmNdmNNNNddNNmdmhmNmmhmhmydmhhmhdNhmNNmdmddmmmmmhhmhdmdNNNNdmNdNhhNNNmNmNNNNdMMNNNNMMM
echo MMMNNMMMMMmmmNNmNdmNNNNddNNmmmhmNNNddhmymmhdmhmmhmNNNhdhhmmmmmyhmhmdNNNNNmmNmNddNNNmNNNMMNmMMNNNNMMM
echo MMMNNMMMMMNdNMMmMmNNNNNmmNNmmNdmNNNdNydhdNmyNdmNymNNNhmddNNdmmhdmhmdmNNNNmmNmNNdNNNmMNNMMNNMMNNNMMMM
echo MMMMMMMMMMNNNMMNNmNMNMNmmNNNmmdmNNNmmhmddNhhNdmNhNNNNdmmdNNddNhmNdNdNNNNNmNNmNddNMNNNNNMMNmNMNMMMMMM



pause >nul
start index.exe